require: rubocop-rspec

AllCops:
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/*.rb'

Style/Documentation:
  Exclude:
    - 'lib/wiki_builder/version.rb' # No need to document `WikiBuilder` there
